config/routes.rb
OutsideIn::Application.routes.draw do
  devise_for :users
  resources :users

  root 'users#home'

  get 'users/sign_in' => 'users#sign_in', as: :sign_in
  resources :profiles, only: :new

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new; end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def home; end

	def sign_in; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OutsideIn</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <header>
  	<ul>
  	  <% if !user_signed_in? %>
  		  <li>
  			  <%= link_to "Sign in", sign_in_path %>
  		  </li>
  		<% end %>
  		<% if user_signed_in? %>
  		  <li>
  			  <%= link_to "Home", root_path  %>
  		  </li>
        <% if current_user.profile.nil?  %>
          <li>
            <%= link_to "Create Profile", new_profile_path  %>
          </li>
        <% end %>
  		<% end %>
  	 <% if user_signed_in? %>
  	   <li>
  	   	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
   	   </li>
  	 <% end %>

  	</ul>

  </header>

  <%= yield %>

</body>
</html>

app/views/users/home.html.erb
<h1> Home </h1>


</div>

app/views/users/sign_in.html.erb
<h3>Sign in</h3>

<div>
  <%= form_for(:user, :url => session_path(:user)) do |f| %>
    <div>
    	<%= f.text_field :email %>
    </div>
    <div>
    	<%= f.password_field :password %>
    </div>
    <div>
    	<%= f.submit 'Sign in' %>
    </div>
  <% end %>